import type { Tables } from '../database.types';

/**
 * Database type for cyclists table.
 * Use this instead of Tables<'cyclists'> throughout the codebase.
 */
export type CyclistDB = Tables<'cyclists'>;

/**
 * Insert type for cyclists table with short_id as optional.
 * short_id is auto-generated by database trigger, so it should be omitted from inserts.
 */
export type CyclistInsert = Omit<CyclistDB, 'id' | 'short_id' | 'created_at' | 'updated_at'> & {
	id?: string;
	short_id?: string;
	created_at?: string | null;
	updated_at?: string | null;
};

/**
 * Type for race result item in RPC responses with flat structure.
 * Used by get_race_results_by_user_short_id RPC function.
 * Includes flattened event, race, and category data (snake_case from DB).
 */
export interface RaceResultRpcItem {
	// Race result fields
	id: string; // Race result short_id (NanoID)
	place: number;
	time: string | null;
	points: number | null;
	created_at: string;
	updated_at: string;

	// Event fields
	event_id: string; // Event short_id (NanoID)
	event_name: string;
	event_date_time: string;
	event_year: number;
	event_city: string;
	event_state: string;
	event_country: string;
	event_status: string;

	// Race fields
	race_id: string; // Race short_id (NanoID)
	race_name: string | null;
	race_date_time: string;

	// Category IDs (for interim navigation)
	race_category_id: string; // Category short_id (NanoID)
	race_category_gender_id: string; // Gender short_id (NanoID)
	race_category_length_id: string; // Length short_id (NanoID)

	// Category types
	race_category_type: string;
	race_category_gender_type: string;
	race_category_length_type: string;
	race_ranking_type: string;
}
