import type { Database, Tables } from '../database.types';

/**
 * Database type for cyclists table.
 * Use this instead of Tables<'cyclists'> throughout the codebase.
 */
export type CyclistTableDB = Tables<'cyclists'>;

/**
 * Insert type for cyclists table.
 * ID is auto-generated by database, so it should be omitted from inserts.
 */
export type CyclistInsertDB = Omit<CyclistTableDB, 'id' | 'created_at' | 'updated_at'> & {
	id?: string;
	created_at?: string | null;
	updated_at?: string | null;
};

/**
 * Auto-generated type for cyclist RPC response.
 * Returned by get_cyclist_by_user_id() RPC function.
 * Includes flattened user, role, and cyclist data (snake_case from DB).
 */
export type CyclistDB =
	Database['public']['Functions']['get_cyclist_by_user_id']['Returns'][number];
