import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '$lib/types/database.types';
import type { Cyclist, CyclistWithRelations } from '$lib/types/domain';
import type { CyclistWithResultsRpcResponse, CyclistInsert } from '$lib/types/db';
import { adaptCyclistWithResultsFromRpc, adaptCyclistFromDb } from '$lib/adapters';

type TypedSupabaseClient = SupabaseClient<Database>;

interface GetCyclistWithResultsByIdParams {
	id: string;
}

/**
 * Get cyclist by ID with race results and full race details.
 * Returns domain CyclistWithRelations type with camelCase fields, or null if not found.
 *
 * Uses optimized RPC function get_cyclist_with_results() for better performance.
 * Single PostgreSQL query with nested JOINs - much faster than multiple requests.
 * Includes race results with full race info, event details, categories, and ranking points.
 * Results are sorted by event date (most recent first).
 *
 * ID parameter is the short_id (public ID), not UUID.
 * RPC function handles short_id → UUID lookup internally at DB level.
 *
 * Returns null when cyclist doesn't exist (expected case).
 * Throws error only for unexpected database issues.
 */
export async function getCyclistWithResultsById(
	supabase: TypedSupabaseClient,
	params: GetCyclistWithResultsByIdParams
): Promise<CyclistWithRelations | null> {
	const { data, error } = await supabase.rpc('get_cyclist_with_results', {
		cyclist_short_id: params.id // Changed: RPC now accepts short_id parameter
	});

	if (error) {
		throw new Error(`Error fetching cyclist: ${error.message}`);
	}

	// Return null if cyclist doesn't exist (expected case)
	if (!data) {
		return null;
	}

	// Use adapter to transform RPC JSONB response → Domain type
	return adaptCyclistWithResultsFromRpc(data as unknown as CyclistWithResultsRpcResponse);
}

/**
 * Create a new cyclist profile linked to an existing user.
 * Returns domain Cyclist type with camelCase fields.
 *
 * IMPORTANT: Cyclist names come from the linked user record.
 * The user must be created first with first_name and last_name before creating the cyclist.
 *
 * Note: short_id is auto-generated by database trigger, so it's omitted from insert.
 */
export async function createCyclist(
	supabase: TypedSupabaseClient,
	cyclist: {
		userId: string; // Required - every cyclist must link to an existing user
		bornYear?: number | null;
		genderId?: string | null;
	}
): Promise<Cyclist> {
	// Prepare insert data - short_id is auto-generated by trigger
	const insertData: CyclistInsert = {
		user_id: cyclist.userId,
		born_year: cyclist.bornYear ?? null,
		gender_id: cyclist.genderId ?? null
	};

	// Type assertion needed because DB trigger auto-generates short_id, but Supabase types expect it
	const { data, error } = await supabase
		.from('cyclists')
		.insert(insertData as never)
		.select()
		.single();

	if (error) {
		throw new Error(`Error creating cyclist: ${error.message}`);
	}

	if (!data) {
		throw new Error('Failed to create cyclist');
	}

	// Use adapter to transform DB type → Domain type
	return adaptCyclistFromDb(data);
}
