import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '$lib/types/database.types';
import type { Organization } from '$lib/types/domain';
import type {
	GetOrganizationByIdParams,
	CreateOrganizationParams,
	UpdateOrganizationParams,
	DeleteOrganizationParams
} from '$lib/types/services';
import { adaptOrganizationFromDb } from '$lib/adapters';

type TypedSupabaseClient = SupabaseClient<Database>;

/**
 * Get all active organizations with event count.
 * Returns domain Organization types with camelCase fields.
 * Filters only active organizations (is_active = true) via RLS.
 * Includes aggregated event count for list view.
 */
export async function getAllOrganizations(supabase: TypedSupabaseClient): Promise<Organization[]> {
	// Query organizations with event count aggregation
	const { data, error } = await supabase
		.from('organizations')
		.select(
			`
			*,
			events:events(count)
		`
		)
		.eq('is_active', true)
		.order('name', { ascending: true });

	if (error) {
		throw new Error(`Error fetching organizations: ${error.message}`);
	}

	// Transform DB types → Domain types and add event count
	return (data || []).map((org) => {
		const adapted = adaptOrganizationFromDb(org);
		// Add event count from aggregation
		return {
			...adapted,
			eventCount: org.events?.[0]?.count ?? 0
		};
	});
}

/**
 * Get single organization by ID (short_id).
 * Returns domain Organization type with camelCase fields.
 * Returns null if organization not found or inactive.
 * Includes event count for consistency with list view.
 */
export async function getOrganizationById(
	supabase: TypedSupabaseClient,
	params: GetOrganizationByIdParams
): Promise<Organization | null> {
	const { data, error } = await supabase
		.from('organizations')
		.select(
			`
			*,
			events:events(count)
		`
		)
		.eq('short_id', params.id)
		.eq('is_active', true)
		.single();

	if (error) {
		// PGRST116 = no rows found - expected when organization doesn't exist
		if (error.code === 'PGRST116') {
			return null;
		}
		// Other errors are unexpected - throw them
		throw new Error(`Error fetching organization: ${error.message}`);
	}

	if (!data) return null;

	// Transform DB type → Domain type and add event count
	const adapted = adaptOrganizationFromDb(data);
	return {
		...adapted,
		eventCount: data.events?.[0]?.count ?? 0
	};
}

/**
 * Create a new organization.
 * Returns domain Organization type with camelCase fields.
 * The short_id is auto-generated by the database trigger.
 */
export async function createOrganization(
	supabase: TypedSupabaseClient,
	params: CreateOrganizationParams
): Promise<Organization> {
	const { data, error } = await supabase
		.from('organizations')
		.insert({
			name: params.name,
			description: params.description ?? null,
			short_id: '' // Empty string triggers auto-generation by database trigger
			// is_active defaults to true
		})
		.select()
		.single();

	if (error) {
		throw new Error(`Error creating organization: ${error.message}`);
	}

	if (!data) {
		throw new Error('No data returned after creating organization');
	}

	return adaptOrganizationFromDb(data);
}

/**
 * Update an existing organization by ID (short_id).
 * Returns domain Organization type with camelCase fields.
 * Only provided fields will be updated (partial update).
 */
export async function updateOrganization(
	supabase: TypedSupabaseClient,
	params: UpdateOrganizationParams
): Promise<Organization> {
	// Build update object with only provided fields
	const updateData: Record<string, string | null> = {};
	if (params.name !== undefined) updateData.name = params.name;
	if (params.description !== undefined) updateData.description = params.description;

	const { data, error } = await supabase
		.from('organizations')
		.update(updateData)
		.eq('short_id', params.id)
		.select()
		.single();

	if (error) {
		// PGRST116 = no rows found - organization doesn't exist
		if (error.code === 'PGRST116') {
			throw new Error(`Organization with ID ${params.id} not found`);
		}
		throw new Error(`Error updating organization: ${error.message}`);
	}

	if (!data) {
		throw new Error('No data returned after updating organization');
	}

	return adaptOrganizationFromDb(data);
}

/**
 * Soft delete an organization by ID (short_id).
 * Sets is_active to false instead of deleting the record.
 */
export async function deleteOrganization(
	supabase: TypedSupabaseClient,
	params: DeleteOrganizationParams
): Promise<void> {
	const { error } = await supabase
		.from('organizations')
		.update({ is_active: false })
		.eq('short_id', params.id);

	if (error) {
		throw new Error(`Error deleting organization: ${error.message}`);
	}
}
