/**
 * Organization Invitations Service
 *
 * Provides CRUD operations for organization owner invitations.
 */

import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '$lib/types/database.types';
import type {
	OrganizationInvitation,
	OrganizationInvitationStatus
} from '$lib/types/domain/organization-invitation.domain';
import type { OrganizationInvitationDB } from '$lib/types/db';
import { adaptOrganizationInvitationFromDb } from '$lib/adapters/organization-invitations.adapter';

type TypedSupabaseClient = SupabaseClient<Database>;

export interface CreateInvitationParams {
	organizationId: string; // UUID (not short_id)
	email: string;
	invitedOwnerName: string;
}

export interface UpdateInvitationStatusParams {
	id: string; // short_id
	status: OrganizationInvitationStatus;
}

export interface IncrementRetryCountParams {
	id: string; // short_id
}

/**
 * Creates a new organization invitation record.
 *
 * @param supabase - Typed Supabase client
 * @param params - Invitation creation parameters
 * @returns Created invitation
 */
export async function createInvitation(
	supabase: TypedSupabaseClient,
	params: CreateInvitationParams
): Promise<OrganizationInvitation> {
	const { data, error } = await supabase
		.from('organization_invitations')
		.insert({
			organization_id: params.organizationId,
			email: params.email,
			invited_owner_name: params.invitedOwnerName,
			short_id: '', // Will be auto-generated by trigger
			status: 'pending'
		})
		.select()
		.single();

	if (error) {
		console.error('[Organization Invitations] Failed to create invitation:', error);
		throw new Error(`Failed to create invitation: ${error.message}`);
	}

	return adaptOrganizationInvitationFromDb(data as OrganizationInvitationDB);
}

/**
 * Gets a pending invitation by email address.
 *
 * @param supabase - Typed Supabase client
 * @param email - Email address to search for
 * @returns Invitation if found and pending, null otherwise
 */
export async function getInvitationByEmail(
	supabase: TypedSupabaseClient,
	email: string
): Promise<OrganizationInvitation | null> {
	const { data, error } = await supabase
		.from('organization_invitations')
		.select()
		.eq('email', email)
		.eq('status', 'pending')
		.single();

	// PGRST116: No rows found - expected for non-existent invitations
	if (error) {
		if (error.code === 'PGRST116') {
			return null;
		}
		console.error('[Organization Invitations] Failed to get invitation by email:', error);
		throw new Error(`Failed to get invitation: ${error.message}`);
	}

	return adaptOrganizationInvitationFromDb(data as OrganizationInvitationDB);
}

/**
 * Gets a pending invitation by organization ID.
 *
 * @param supabase - Typed Supabase client
 * @param organizationId - Organization UUID
 * @returns Invitation if found and pending, null otherwise
 */
export async function getInvitationByOrganizationId(
	supabase: TypedSupabaseClient,
	organizationId: string
): Promise<OrganizationInvitation | null> {
	const { data, error } = await supabase
		.from('organization_invitations')
		.select()
		.eq('organization_id', organizationId)
		.eq('status', 'pending')
		.single();

	// PGRST116: No rows found - expected for non-existent invitations
	if (error) {
		if (error.code === 'PGRST116') {
			return null;
		}
		console.error('[Organization Invitations] Failed to get invitation by organization:', error);
		throw new Error(`Failed to get invitation: ${error.message}`);
	}

	return adaptOrganizationInvitationFromDb(data as OrganizationInvitationDB);
}

/**
 * Updates the status of an invitation.
 *
 * @param supabase - Typed Supabase client
 * @param params - Update parameters
 * @returns Updated invitation
 */
export async function updateInvitationStatus(
	supabase: TypedSupabaseClient,
	params: UpdateInvitationStatusParams
): Promise<OrganizationInvitation> {
	const { data, error } = await supabase
		.from('organization_invitations')
		.update({ status: params.status })
		.eq('short_id', params.id)
		.select()
		.single();

	if (error) {
		console.error('[Organization Invitations] Failed to update invitation status:', error);
		throw new Error(`Failed to update invitation status: ${error.message}`);
	}

	return adaptOrganizationInvitationFromDb(data as OrganizationInvitationDB);
}

/**
 * Gets pending invitations that need a retry (for cron job).
 * Returns invitations where:
 * - status = 'pending'
 * - retry_count < 3
 * - last_invitation_sent_at is older than 7 days
 *
 * @param supabase - Typed Supabase client
 * @returns Array of invitations needing retry
 */
export async function getPendingInvitationsForRetry(
	supabase: TypedSupabaseClient
): Promise<OrganizationInvitation[]> {
	const sevenDaysAgo = new Date();
	sevenDaysAgo.setDate(sevenDaysAgo.getDate() - 7);

	const { data, error } = await supabase
		.from('organization_invitations')
		.select()
		.eq('status', 'pending')
		.lt('retry_count', 3)
		.lt('last_invitation_sent_at', sevenDaysAgo.toISOString());

	if (error) {
		console.error('[Organization Invitations] Failed to get pending invitations for retry:', error);
		throw new Error(`Failed to get pending invitations: ${error.message}`);
	}

	return data.map((item) => adaptOrganizationInvitationFromDb(item as OrganizationInvitationDB));
}

/**
 * Increments the retry count and updates last_invitation_sent_at timestamp.
 *
 * @param supabase - Typed Supabase client
 * @param params - Invitation ID parameters
 * @returns Updated invitation
 */
export async function incrementRetryCount(
	supabase: TypedSupabaseClient,
	params: IncrementRetryCountParams
): Promise<OrganizationInvitation> {
	// First, get the current retry count
	const { data: currentData, error: fetchError } = await supabase
		.from('organization_invitations')
		.select('retry_count')
		.eq('short_id', params.id)
		.single();

	if (fetchError) {
		console.error('[Organization Invitations] Failed to fetch current retry count:', fetchError);
		throw new Error(`Failed to fetch invitation: ${fetchError.message}`);
	}

	// Increment retry count and update timestamp
	const { data, error } = await supabase
		.from('organization_invitations')
		.update({
			retry_count: currentData.retry_count + 1,
			last_invitation_sent_at: new Date().toISOString()
		})
		.eq('short_id', params.id)
		.select()
		.single();

	if (error) {
		console.error('[Organization Invitations] Failed to increment retry count:', error);
		throw new Error(`Failed to increment retry count: ${error.message}`);
	}

	return adaptOrganizationInvitationFromDb(data as OrganizationInvitationDB);
}

/**
 * Deletes all invitations for an organization by organization ID.
 * Used during organization deactivation to clean up pending invitations.
 *
 * @param supabase - Typed Supabase client
 * @param organizationId - Organization UUID
 * @returns Number of invitations deleted
 */
export async function deleteInvitationByOrganizationId(
	supabase: TypedSupabaseClient,
	organizationId: string
): Promise<number> {
	const { error, count } = await supabase
		.from('organization_invitations')
		.delete({ count: 'exact' })
		.eq('organization_id', organizationId);

	if (error) {
		console.error('[Organization Invitations] Failed to delete invitations:', error);
		throw new Error(`Failed to delete invitations: ${error.message}`);
	}

	return count ?? 0;
}
