import type { SupabaseClient } from '@supabase/supabase-js';
import type { Database } from '$lib/types/database.types';
import type { SetRoleRequest, UserResponse } from '$lib/types/services/users';
import type { UserWithRelationsRpcResponse } from '$lib/types/db';
import { adaptUserWithRelationsFromRpc } from '$lib/adapters';

/**
 * Get the current user's enriched data including role and related entities.
 * Note: In most cases, you should use event.locals.user from hooks instead of calling this directly.
 * @param supabase - Supabase client instance
 * @returns UserResponse with enriched user data or error
 */
export const getMyself = async (supabase: SupabaseClient<Database>): Promise<UserResponse> => {
	try {
		// Get the current authenticated user
		const {
			data: { user: authUser },
			error: authError
		} = await supabase.auth.getUser();

		if (authError || !authUser) {
			return {
				error: {
					status: 401,
					name: 'AuthError',
					message: 'Not authenticated'
				}
			};
		}

		// Fetch enriched user data (RPC uses auth.uid() when no parameter provided)
		const { data: userData, error: userError } = await supabase.rpc('get_user_with_relations');

		if (userError || !userData) {
			return {
				error: {
					status: 500,
					name: 'UserDataError',
					message: 'Failed to fetch user data'
				}
			};
		}

		return {
			data: adaptUserWithRelationsFromRpc(userData as unknown as UserWithRelationsRpcResponse)
		};
	} catch (error) {
		return {
			error: {
				status: 500,
				name: 'FetchError',
				message: 'Failed to fetch user'
			}
		};
	}
};

/**
 * Update a user's role.
 * Only admins and organizer admins can update user roles (enforced by RLS).
 * @param supabase - Supabase client instance
 * @param params - User ID and new role ID
 * @returns UserResponse with updated user data or error
 */
export const updateUser = async (
	supabase: SupabaseClient<Database>,
	{ roleId, userId }: SetRoleRequest
): Promise<UserResponse> => {
	try {
		// Update the user's role in the database
		const { error: updateError } = await supabase
			.from('users')
			.update({ role_id: roleId })
			.eq('id', userId);

		if (updateError) {
			return {
				error: {
					status: 400,
					name: 'UpdateError',
					message: updateError.message
				}
			};
		}

		// Fetch the user's short_id first (userId is UUID)
		const { data: userRow, error: userRowError } = await supabase
			.from('users')
			.select('short_id')
			.eq('id', userId)
			.single();

		if (userRowError || !userRow) {
			return {
				error: {
					status: 500,
					name: 'UserDataError',
					message: 'Failed to fetch user'
				}
			};
		}

		// Fetch the updated enriched user data using short_id
		const { data: userData, error: userError } = await supabase.rpc('get_user_with_relations', {
			user_short_id: userRow.short_id
		});

		if (userError || !userData) {
			return {
				error: {
					status: 500,
					name: 'UserDataError',
					message: 'Failed to fetch updated user data'
				}
			};
		}

		return {
			data: adaptUserWithRelationsFromRpc(userData as unknown as UserWithRelationsRpcResponse)
		};
	} catch (error) {
		return {
			error: {
				status: 500,
				name: 'FetchError',
				message: 'Failed to update user'
			}
		};
	}
};

export interface CreateUserWithRoleParams {
	authUserId: string;
	firstName: string;
	lastName: string;
	roleName: string; // Role name like 'organizer_owner', 'cyclist', etc.
}

/**
 * Creates a new user record in the public.users table with a specific role.
 * Used during invitation acceptance flow to create the user's profile.
 * @param supabase - Supabase client instance
 * @param params - User creation parameters
 * @returns Created user's UUID
 */
export const createUserWithRole = async (
	supabase: SupabaseClient<Database>,
	params: CreateUserWithRoleParams
): Promise<string> => {
	// First, get the role ID by role name
	const { data: roleData, error: roleError } = await supabase
		.from('roles')
		.select('id')
		.eq('name', params.roleName)
		.single();

	if (roleError || !roleData) {
		throw new Error(`Failed to find role: ${params.roleName}`);
	}

	// Create the user record
	const { data: userData, error: userError } = await supabase
		.from('users')
		.insert({
			auth_user_id: params.authUserId,
			first_name: params.firstName,
			last_name: params.lastName,
			role_id: roleData.id,
			short_id: '' // Will be auto-generated by trigger
		})
		.select('id')
		.single();

	if (userError || !userData) {
		throw new Error(`Failed to create user: ${userError?.message || 'Unknown error'}`);
	}

	return userData.id;
};

export interface LinkUserToOrganizationParams {
	userId: string; // User UUID
	organizationId: string; // Organization UUID
}

/**
 * Creates an organizer record linking a user to an organization.
 * Used during invitation acceptance to make the user an owner of the organization.
 * @param supabase - Supabase client instance
 * @param params - Link parameters
 * @returns Created organizer record's UUID
 */
export const linkUserToOrganization = async (
	supabase: SupabaseClient<Database>,
	params: LinkUserToOrganizationParams
): Promise<string> => {
	const { data, error } = await supabase
		.from('organizers')
		.insert({
			user_id: params.userId,
			organization_id: params.organizationId,
			short_id: '' // Will be auto-generated by trigger
		})
		.select('id')
		.single();

	if (error || !data) {
		throw new Error(`Failed to link user to organization: ${error?.message || 'Unknown error'}`);
	}

	return data.id;
};
